// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzfdRy3qFu7yNHR_9Kn2xvRFqekQijYc',
    appId: '1:1026104450343:android:c33f2497933d0400e29d02',
    messagingSenderId: '1026104450343',
    projectId: 'chat-app-4289f',
    storageBucket: 'chat-app-4289f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegpEDsa4M2PazLYcGCXpFw58QKSc14BM',
    appId: '1:1026104450343:ios:3be26ec0fa66119ee29d02',
    messagingSenderId: '1026104450343',
    projectId: 'chat-app-4289f',
    storageBucket: 'chat-app-4289f.appspot.com',
    androidClientId: '1026104450343-66l6ohgkeedbdqjg2jrsu58f82kbru10.apps.googleusercontent.com',
    iosClientId: '1026104450343-em2ask6ksaptfgov966n9elh1shbvdhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
